### PR TITLE
Add a section for structured data mark up

### PR DESCRIPTION
**Pull request by TommyChanthaboune**
Created a section for Structured Data Mark up
Moved and edited Facebook Tips and merged it into this new section

### CODE REVIEW

**Comment by marcelmoreau** [comment]
It feels like there is not much here for Imarcians to sink their teeth into.
- Search Engines: Should we rename this to be [Rich Snippets](https://developers.google.com/structured-data/rich-snippets/)? Can we show at least one example that would be relevant to the sites we create? Maybe a news detail?
- Social Media: Should we rename this section to be **Facebook** if there are no other other social media that play with OG? Can we show at least one example that would be relevant to the sites we create? 

By including examples, Imarcians can quickly copy and paste the common scenarios into their projects. It could also inspire people to want to look into these things more if we show their benefits.
If we cannot easily think of examples, maybe we do not need this topic after all?
- Minor: please make instances of **mark up** be **markup**.

**Comment by ghost** [comment]
Twitter uses ogtags but can be further refined with twitter tags (i.e. it
will take the ogtag for title if there is no twitter title defined).
LinkedIn is also og tags. I'd recommend mentioning them rather than
addressing only facebook.

On Mon, Apr 4, 2016 at 8:46 PM, Marcel notifications@github.com wrote:

> It feels like there is not much here for Imarcians to sink their teeth
> into.
> 
>    -
> 
>    Search Engines: Should we rename this to be Rich Snippets
>    https://developers.google.com/structured-data/rich-snippets/? Can we
>    show at least one example that would be relevant to the sites we create?
>    Maybe a news detail?
>    -
> 
>    Social Media: Should we rename this section to be _Facebook_ if there
>    are no other other social media that play with OG? Can we show at least one
>    example that would be relevant to the sites we create?
> 
> By including examples, Imarcians can quickly copy and paste the common
> scenarios into their projects. It could also inspire people to want to look
> into these things more if we show their benefits.
> If we cannot easily think of examples, maybe we do not need this topic
> after all?
> - Minor: please make instances of _mark up_ be _markup_.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/imarc/handbook/pull/4#issuecomment-205562697

## 

[image: iMarc Logo]

_Shawna O'Neal_ • Jr. Web Engineer • Imarc, A Digital Agency
shawna@imarc.com victoria@imarc.com • 978.462.8848

**Comment by TommyChanthaboune** [comment]
- Added Examples for Schema.org and Open Graphj markup
- Added References to tools for debugging and validation
- Rewritten some parts

Search Engines only support a few content types that can be rich snippets. I'm sure the list I included will be subject to change sooner or later.

Like @ShawnaOneal said, many other social media platform uses Open Graph Protocol so it is worth investing time into.

There is a learning curve with structured data so it's nothing you can really copy and paste into a project. You just have to be aware of the content types that can benefit and then reference the docs later.

**Comment by marcelmoreau** [comment]
Thanks for this. Few more things:
- This sentence appears under **Open Graph**: _Content that will be shared heavily on social media is recommended to use Schema.org and Open Graph Protocol._ Should this be moved to the intro copy under **Structured Data Markup**?
- When reading through the Schema.org section, I am not sure what I am looking at. What does the product markup do? Can we have an screenshot/image associated with the product markup example?
- Can we move the frozen image after the list of supported content types, and then include a description with it. Something like "Note how this search result includes rating/voting information. This is derived from Schema's ....." 
- We could probably remove the Bing Rich Snippet Support. We could probably remove the Schema test tool link

**Comment by TommyChanthaboune** [comment]
1. ) Sure

2.) This is an example markup for structured data for a product. If a person search for this product, it will potentially appear as a rich snippet if it ranks high enough. Otherwise the markup explicitly define data for crawlers to easily index instead of infering from markup.

3.) Sure

4.) Schema.org works for all search engines so it's good to mention. No this is a good resource to help developers mark up their content. I use this a lot when I'm testing stuff.

**Comment by marcelmoreau** [comment]
2) We just need to make this clearer to Imarcians/users who will be reading this. Should we find an example in the wild and copy its markup and post a screenshot? Or make our own screenshot based on your markup

4) If we keep the Schema test tool link, can we at least combine it with the Open Graph tool link at the end of the section? Both sort of ruin the flow. Maybe there is one area at the bottom of the section that lists the tools and other links

**Comment by TommyChanthaboune** [comment]
2.) Yep ! I will do the later
4.) Sure

**Comment by ghost** [comment]
If you want resources for social media tags, F_acebook_ has both:

https://developers.facebook.com/docs/sharing/best-practices#tags
https://developers.facebook.com/docs/sharing/best-practices#tags

and

http://goog_1825736470
https://developers.facebook.com/docs/sharing/webmasters

_Twitter_ cards have:

https://dev.twitter.com/cards/markup

cards can be validated here: https://cards-dev.twitter.com/validator
https://cards-dev.twitter.com/validator

_Linked-in_ will use the same open-graph tags as facebook, but facebook has
some fb-specific tags that linked-in won't inherit. (i.e. fb:author, which
gets used with fb posts that have type article or blog and which offer a
hyperlink to the content author's facebook page within the post).

Not sure if any of that would be useful to include for reference.

On Wed, Apr 6, 2016 at 6:08 PM, Tommy Chanthaboune <notifications@github.com

> wrote:
> 
> 2.) Yep ! I will do the later
> 3.) Sure
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/imarc/handbook/pull/4#issuecomment-206591610

## 

[image: iMarc Logo]

_Shawna O'Neal_ • Jr. Web Engineer • Imarc, A Digital Agency
shawna@imarc.com victoria@imarc.com • 978.462.8848

**Comment by TommyChanthaboune** [comment]
I used a simplified version of IMDb's mark up with the Frozen rich snippet instead of creating my own.

Added social media rich objects Images
Added extracted data image

Moved testing tools into it's own section
Moved blurb about OGP underneath the main heading

**Comment by TommyChanthaboune** [comment]
@marcelmoreau or @ShawnaOneal  do you have anymore comments on this pull request ? We should open this up to the rest of UX as well.

**Comment by ghost** [comment]
The facebook screenshot isn't from markup, it was put together manually and doesn't actually reflect the tags. I'll grab you a shot of it working and email it to you, give me 5-ish minutes.

**Comment by marcelmoreau** [comment]
If we open it up, it would just drag and drag. We can just merge it when the screenshot is done and then send an update to everyone. If anyone feels strongly about anything, they will let us know.

**Comment by TommyChanthaboune** [comment]
@ShawnaOneal thank you

@marcelmoreau ok

**Comment by marcelmoreau** [comment]
1. There are two links here with the text _For a complete list of types and example markup._ 
   - One points to schema.org. I would expect to find this _at the end_ of the entire Schema.org section. Plase change its copy to something that is not a run-on sentence like _View a complete list of content types and example markup_
   - The other follows a LinkedIn object but points to Facebook's OG docs. Please find a more relevant home for this if we are relating it to Facebook stuff. Please also change its link copy to differ from the previous link.
2. Can we take the Google and Bing unordered lists and display them side-by-side via **.columns**? I think we will need to add this style to the CSS.
3. The Open Graph Example code block has a Facebook Specific comment at its top but then shows twitter markup as well. Is this on purpose? It is confusing.

**Comment by TommyChanthaboune** [comment]
Ok, these edits are pushed

**Comment by marcelmoreau** [comment]
Made some edits:
- @TommyChanthaboune your screenshots were huge! Not sure what you're using to do that but these are now like 1/6 the size they were before. Plus, I bet you did not crunch them :)
- moved some stuff around
- provided more descriptive alternate text for screenreaders
- the columns of lists were breaking (just missing cloding tag)

If people want to look once more, we can merge after

**Comment by TommyChanthaboune** [comment]
Ha I'm glad you caught that. I dunno what made it blow up like it did.

You should go ahead and merge since you are heading up this project. If someone else find's an issue they can open one or create a pull request.

**Pull request merged**
