### PR TITLE
adding SVG documentation

### PR DESCRIPTION
**Pull request by marcelmoreau**

### CODE REVIEW

**Comment by marcelmoreau** [comment]
Anyone?

**Comment by keyesatimarc** [comment]
What you have there is good. Did we want to add a bit about methods for including the code inline vs. using an image tag?

**Comment by mbfitz** [comment]
I agree with @keyesatimarc - we should probably add a note about when to use the code and when to just include it as an image. Also maybe something about utilizing classes on the elements to target via css/js?

**Comment by mbfitz** [comment]
@marcelmoreau - may also want to mention removing any doctype properties from the SVG code in this line "Remove any `height`, `width`, `title` and `style` information...."

**Comment by mbfitz** [comment]
+1

**Comment by khamer** [comment]
+1

**Pull request merged**
