### PR TITLE
adding source maps content and image

### PR DESCRIPTION
**Pull request by marcelmoreau**
This should be a requirement IMO. I picked the five most recently edited projects in Gitlab...none of them utilized a sourcemap. Thoughts?

This also raises another question of "should we officially 'outlaw' usage of the server-side .scss tool' that we use?". It cannot handle @imports

### CODE REVIEW

**Comment by TommyChanthaboune** [comment]
Source maps are super useful, I'm fine with making it a best practice. Of those projects did you check whether the source maps were inline and a part of the generated CSS or the external file ignored and not committed to the repo ? I imagine those projects in the repos are distributed as production ready code and won't have dev stuff in it like source maps.

As far as "outlawing" server side sass compiling, I think it is a bit out of scope here. Not all server side solutions have the same problems we have. I mean technically speaking, `.scss` files are still being transpiled on a server. It is just happening locally not remotely. Also worth mentioning SASS was built with a server side language Ruby and now Dart. So to suggest not to use a server side solution would be technically wrong.

**Comment by khamer** [comment]
I like sourcemaps and agree with Tommy's thoughts - maybe they're there and inline? I'm surprised if we're not using them.

I think we should be using local solutions for compiling Sass for all new projects (probably Laravel Mix for now.) I'll even take the server-side Sass stuff out of Padstone if we want.

That said, I agree with Tommy again, Handbook doesn't seem like the right place to document that. If you really want to push for only client side sass on all projects, then front end devs should take on the tasks of converting all of our existing projects using server side sass. (That doesn't seem worth it to me. Oh and the serverside stuff *can* do `@import` statements.)


**But most importantly**, this chunk work needs regardless:

* This seems like a strange place in the doc to put this content
* The entire frontend section of Handbook doesn't really mention Sass or any other Sass conventions - we might want to start with that before we add this piece. This wiki page is pretty old now, but I feel like a bunch of this content would make sense to update and port to Handbook before we add a comment on sourcemaps: http://wiki.imarc.net/SASS#Coding_Style
* Your heading isn't a heading
* Sourcemaps are really a solution from mapping from *compiled CSS* to the *source Sass* - not really related to minification

**Comment by jeffturcotte** [comment]
I agree with making **external** source map generation a documented best practice. Source maps can be used across all environments if they are generated to an external file and not inline. When in an external file, they only get loaded when devtools are open ([source](https://blog.sentry.io/2015/10/29/debuggable-javascript-with-source-maps.html)).

Build artifacts are committed/not-committed to the repo on a per project basis, so I might leave out anything related to that. If the artifacts are getting committed, then sourcemaps should be in there.

I also agree with Tommy that saying no to 'server-side compilation' as a term is a little misguided. We should instead recommend tooling and where it runs doesn't matter. The leafo PHP scss compiler has shown its weaknesses with very large files and too many @imports.

Anything built on top of [libsass](http://sass-lang.com/libsass) will work best for compilation. Almost all node tooling (laravel-mix, pure webpack, gulp-sass, etc) uses the node-sass lib (built on top of libsass), while the ruby sass libraries should be fine as well. **The standard should be anything node-sass based IMO.**

You all can fight about where this actually goes in the document. I have no opinions there. :)

Edit: I agree with @khamer that we shouldn't convert old projects unless they are very active and we really want to. I've done this with 2 sites already, and it took longer than I thought it would in both cases, but the end result is nice.

**Comment by TommyChanthaboune** [comment]
+1 on this specific pull request.


On a side note:

**Libsass** is definitely the best option right now but we should keep an eye on the officially supported Dart implementation. I think I read somewhere that Dart is 1.5x slower than Libsass but 5/6x faster than Ruby. The trade off being that the Dart implementation is way more easy to extend and improve on than Libsass' C implementation especially since one of the maintainers left the project. I wouldn't be surprised if they moonlighted Libsass to put more resources on the Dart implementation. It's also worth mentioning they are trying to build the new implementation so the magnitude of NPM packages that rely on libsass can seamlessly migrate to the new implementation.

**Comment by marcelmoreau** [comment]
I've made copy changes, making this a strong recommendation.

**Pull request closed without merging**
